name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
    - name: Install dependencies
      run: |
        pip3 install numpy
