name: Run tests

on: [push]

jobs:
  py_three_nine:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Check cmake
      run: |
        cmake --version
    - name: run install
      run: |
        python3 setup.py install
    - name: install torch for testing only
      run: |
        pip3 install torch
    - name: run unit tests
      run: |
        cd test
        python3 runtests.py

  py_three_eleven:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Check cmake
      run: |
        cmake --version
    - name: run install
      run: |
        python3 setup.py install
    - name: install torch for testing only
      run: |
        pip3 install torch
    - name: run unit tests
      run: |
        cd test
        python3 runtests.py
