name: Run tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Check cmake
      run: |
        cmake --version
    - name: run install
      run: |
        python3 setup.py install
    - name: run unit tests
      run: |
        cd test
        python3 test.py
